### ISSUE TITLE
Run 3 Doesnt work so prob just replace it.

### ISSUE THREAD

**Issue by TheOneAndOnlyPenguin** [useclassplay/useclassplay.github.io#14]
run 3 doesnt work

**Comment by TheOneAndOnlyPenguin** [comment]
I don't wanna do it tho.
so yall do it :)

**Comment by bahabryra** [comment]
brah
    On Tuesday, December 3, 2024 at 10:39:15 AM CST, MrPenguin ***@***.***> wrote:  
 
 


I don't wanna do it tho.
so yall do it :)

**Comment by bahabryra** [comment]
brah

**Comment by TheOneAndOnlyPenguin** [comment]
oh your here Riyad?
never knew you were in classplay.

**Comment by SprintingSnail69** [comment]
lol

**Comment by cobblesteve01** [comment]
Nevermind, looks like it ran into an issue again. Looks like we have to replace the files for the third time.

**Comment by SprintingSnail69** [comment]
bruh why just let him be

**Comment by cobblesteve01** [comment]
Alright. After thorough testing, it's a problem with the chromebooks. I've tested Run 3 on my personal computer, and it works perfectly fine. I'm going to close this issue as unfixable considering that every version of Run 3 I've tried doesn't work.
