### ISSUE TITLE
[BUG] Geometry Dash Long Load Times

### ISSUE THREAD

**Issue by SyntaxError52** [useclassplay/useclassplay.github.io#17]
### **what's your issue?**
describe this bug ⬇️

When I try to play a level on GD it takes like 30 years to load

### **how can we make this issue happen again? (for testing)**
please guide us through the process:
1. Go to Games
2. Click on GD
3. Try playing a level

### **what function was it supposed to ACTUALLY perform (instead of bug)?**
describe what was supposed to happen...

open the level.

### **any screenshots?**
please add pictures so we can better understand your problem

oh hail nah bruh I ant doin all that

### **computer**
 - operating system: ChromeOS
 - os version: 52
 - browser: Chrome
 - browser version 122
 
### **notes and other stuff**
add additional stuff

nah bruh

**Comment by cobblesteve01** [comment]
Sorry, but that's an unfixable issue. Level load time all depends on the device. Considering the specs of a Chromebook (4 GB of RAM, a 1.1 GHz processor, etc.)

I'm going to close this as not planned until I find a more optimized one.

Until then, you'll have to deal with this one. If you find an alternitive, just leave a comment on the issue with a link to it and I'll check it out.

Best, 

cobblesteve01

**Comment by SyntaxError52** [comment]
# I DONT CARE

**Comment by bahabryra** [comment]
shut your trap if you dont sad about that YOU FIX IT or FIND ANOTHER PLACE TO BE

sorry charlie this is me when i get mad
