### ISSUE TITLE
skibidi

### ISSUE THREAD

**Issue by TheOneAndOnlyPenguin** [useclassplay/useclassplay.github.io#20]
security proxy

**Comment by TheOneAndOnlyPenguin** [comment]
can I change the url

**Comment by bahabryra** [comment]
Alternate Links

| 
| 
|  | 
Alternate Links


 |

 |

 |




    On Tuesday, December 10, 2024 at 09:55:28 AM CST, MrPenguin ***@***.***> wrote:  
 
 


can I change the url

**Comment by TheOneAndOnlyPenguin** [comment]
?

**Comment by bahabryra** [comment]
https://easysciencetools.github.io/lnk

**Comment by SprintingSnail69** [comment]
what's the problems
