### ISSUE TITLE
Good News Bad News

### ISSUE THREAD

**Issue by bahabryra** [useclassplay/useclassplay.github.io#21]
The Good News is I talked to light speed and they said the **MIGHT** unblock it under 1 condition

_**that's the bad news**_ the condition is we make it possible for teachers  to control if they can play games/watch movies ect. and of course  _**REMOVE THE PROXY**_

**Comment by cobblesteve01** [comment]
yep no. this is an unblocked games website. we don't let those people control us

**Comment by bahabryra** [comment]
thats what im talking about

**Comment by cobblesteve01** [comment]
for the students, always have been and always will be. no bargaining with the systems that exist to block websites like this.
