### ISSUE TITLE
about:blank detector

### ISSUE THREAD

**Issue by bahabryra** [useclassplay/useclassplay.github.io#26]
### **is your feature request related to a problem? Please describe.**
not really
### **describe the solution you'd like**
When you open the about:blank anything talking or doing the about:blank 
for example when you open an about:blank cloak instead of showing the button to open an about:blank it says ### _**"YOUR ALREADY IN AN ABOUT:BLANK YOU PUNKS**_
### **describe alternatives you've considered**
idk
### **additional context**
bob the builder can he build it bob the builder no he cant bob the builder can he build it bob the builder no he cant bob the builder can he build it bob the builder no he cant and 1 last thing 
 

> ### _**CHECK YOUR FRIGGIN  EMAIL**_

**Comment by cobblesteve01** [comment]
I'll consider it
