### ISSUE TITLE
WHAT WHY

### ISSUE THREAD

**Issue by bahabryra** [useclassplay/useclassplay.github.io#27]

**Comment by SprintingSnail69** [comment]
im sry we got in trouble. its over man

**Comment by bahabryra** [comment]
NOOOOOOOOOOOOOO PLSSSSSSSSSSSSSSS NOOOOOOOOOOOO PLSSSSSSSSSSSSSS
:being sad:
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
:deppersiion takeing over:
why...
:dies from depression:
x| 
(last words were SAVE CLASSBOARD/PLAy)
man i just got some domains for us :(
:upset:
COME ON I MEAN WE CANT LET A BUNCH OF ADULTS MESS UP ALL ARE HARD WORK IM SICK OF IT
:determined:
MAN, COME ON CHARLIE YOUR GONNA LET A BUNCH OF GROWN UPS RUIN YOUR HARD WORK
