### ISSUE TITLE
vidlink does not work (refused to connect)

### ISSUE THREAD

**Issue by bahabryra** [useclassplay/useclassplay.github.io#4]

**Comment by bahabryra** [comment]
and It doesn't even show if your on lighspeed

**Comment by bahabryra** [comment]
(the Movie buttons)

**Comment by bahabryra** [comment]
![Screenshot 2024-11-14 8 44 36 AM](https://github.com/user-attachments/assets/8c1bcbf1-f50e-4a70-b81c-620e9acf0510)

**Comment by cobblesteve01** [comment]
This is a known issue, we are working to fix it. This is due to The Movie DB being blocked.

**Comment by bahabryra** [comment]
that makes no sense I think it has x-frame cause its not working on not filters

**Comment by cobblesteve01** [comment]
No, it's because The Movie DB is blocked. All the images and titles appear from The Movie DB. There are no image sources in the HTML code.
